### ISSUE TITLE
Is it possible to have a release version ??

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom-jdbc#12]
Hello,
is it possible to have a release version ? (this apply for the others plugin) :-)

**Comment by cescoffier** [comment]
A 0.5 version has been cut 21 days ago (https://github.com/wisdom-framework/wisdom-jdbc/releases/tag/wisdom-jdbc-0.5).

There are no changes since this release.

**Comment by hboumedane** [comment]
thanks, and for the others , orientdb for exemple !!!

**Comment by cescoffier** [comment]
You should ask on the OrientDB project. Jonathan is managing this module.

2015-02-03 10:45 GMT+01:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
ok will do that !!
you can close this issue.

**Comment by barjo** [comment]
Hi,

wisdom-orientdb has been released too, 23 days ago.
https://github.com/wisdom-framework/wisdom-orientdb/releases

Release are deployed on the maven central and sonatype repositories as well
as on the github release page.

Here is the last release dependency declaration:

<dependency>
  <groupId>org.wisdom-framework</groupId>
  <artifactId>wisdom-orientdb-object</artifactId>
  <version>0.2.2</version>
</dependency>



Best,

Jonathan
