### ISSUE TITLE
Is it possible to have two PU ??

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom-jdbc#13]
Hi,

I have to persistence.xml file for my project, one for production(src/main/ressources/META-INF) and one for test(src/test/ressources/META-INF) .

how can I tell tests to use the persistence for the test purpose.

**Comment by cescoffier** [comment]
No this is not supported.

2015-04-02 17:04 GMT+02:00 hboumedane <notifications@github.com>:
