### ISSUE TITLE
Error while retrieving entity manager

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom-jdbc#15]
Hello,

I have a datasource that is configured to use a H2 in memory database for integration tests.
I managed to copy the persitence.xml test file in the target/classses/META-INF to be used by IT.
when i run IT i got an exception like :  

```java
4/8/15 9:51:31 AM (S) JTAEntityCrud.error : [Unit : test-PU, Entity: models.User, Id: int] - the transactional block has thrown an exception, rollback the transaction
java.lang.IllegalStateException: Error while retrieving entity manager

Caused by: <openjpa-2.3.0-r422266:1540826 nonfatal general error> org.apache.openjpa.persistence.PersistenceException: Table "USERS" not found; SQL statement:
ALTER TABLE Users ADD COLUMN birthday TIMESTAMP [42102-184] {stmnt 110038171 ALTER TABLE Users ADD COLUMN birthday TIMESTAMP} [code=42102, state=42S02]
	at org.apache.openjpa.jdbc.meta.MappingTool.record(MappingTool.java:559)
```

**Comment by cescoffier** [comment]
Well, I think it's pretty clear, the "USERS" table was existing in the database. You should create it, or enable the schema generation (see OpenJPA documentation for this)

**Comment by hboumedane** [comment]
still the same error even when i tell openjpas to generate the schema 

here how I enable schema generation :  

```xml
        <properties>
            <property name="openjpa.jdbc.SynchronizeMappings"
                     value="buildSchema(SchemaAction='dropDB,createDB,add,OpenJPATables=true')"/>
        </properties>
```

**Comment by cescoffier** [comment]
Try with a clean database.

**Comment by hboumedane** [comment]
it's an H2 in memory database !!!

**Comment by cescoffier** [comment]
So, it's an issue with openjpa not with wisdom. You should refer to the openjpa documentation.

**Comment by hboumedane** [comment]
ok thanks for the help.
I found a lot of unanswered question about this topic. openjpa seem's to have a lack of useful functionality.
so it's time add support for other jpa provider like toplink, hibernate....

**Comment by cescoffier** [comment]
we accept contribution ;-)

I'm not sure it's an issue in the openjpa feature set, as I use it quite a lot, and never have such issue.

**Comment by hboumedane** [comment]
:-) ok , I will continue to investigate ..

**Comment by barjo** [comment]
@hboumedane sure, it would be great if you could add support any other jpa provider that you feel would be more suitable. 
Feel free to open the issue on openjpa if it came from them, and add a reference to the issue here.

**Comment by hboumedane** [comment]
will do my best to help

**Comment by hboumedane** [comment]
solved, it was an annotation error.

**Comment by cescoffier** [comment]
What kind of error ? Just to have a trace.

**Comment by hboumedane** [comment]
I was overriding the annotation with orm.xml file and using unique attribute for the id.
the hsql don't allow this.
